baseURL: "https://saraz9.github.io/" 
title: Sara Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Keywords
          url: tags/
          weight: 4
        - name: Projects
          url: projects/
          weight: 1
        - name: Education
          url: education/
          weight: 3
        - name: Experience
          url: experience/
          weight: 2
        - name: About Me
          url: life/

params:
    description: "I am Sara Zhang, and here is a place where you can learn about me."
    author: Sara Zhang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: ""
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","education","keywords"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sara Zhang
          subtitle: "I graduated twice from UBC and still haven’t stopped learning. I’m passionate about software development, machine learning, data science, and mathematics. I find joy in solving complex puzzles, especially those with over 2,000 pieces. I recently discovered a love for digital drawing as a way to relax and express myself. I'm a lifelong learner, always curious and open to meeting life as it is."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Sara Zhang
          buttons:
            - name: Projects
              url: projects/
            - name: Experience
              url: experience/
            - name: Education
              url: education/
            - name: Tags
              url: tags/
#            - name: Archive
#              url: archive/
            - name: About Me
              url: life/

    socialIcons:
        - name: Email
          url: mailto:zhangxiyu100@gmail.com
        - name: GitHub
          url: https://github.com/SaraZ9
        - name: linkedin
          url: https://www.linkedin.com/in/xiyusarazhang/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sara Z."
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2